### ISSUE TITLE
Problem running client

### ISSUE THREAD

**Issue by paulhendrix** [funador/react-confirm-email#1]
Failed to compile
./src/App.js
Module not found: Can't resolve 'react-toastify/dist/ReactToastify.css' in 'C:\temp\2019-04\react-confirm-email\client\src'
This error occurred during the build time and cannot be dismissed.

**Comment by funador** [comment]
Have you run `npm install` to grab all the packages required to start the project.  If you have, try deleting your `./node_modules` folder and running `npm install` again. Drop another comment here if that doesn't work.

**Comment by paulhendrix** [comment]
I deleted whole folder, git cloned all
in client folder: 
npm install 
npm start and the same error appears :(
There is no ReactToastify.css file
System: Windows 10 64bit
Node v10.14.2

**Comment by funador** [comment]
Something must have changed with that package and now the css is imported by default.  You should be able to just comment out that line and it should work. 

Change has been pushed.

**Comment by paulhendrix** [comment]
That solves it!
Thanks @funador

**Comment by funador** [comment]
welcome @paulhendrix
